const {v4: uuidv4} = require('uuid');

async function createData(){
    const roles = [
        {rol_id: 1, rol_descripcion: "root"},
        {rol_id: 2, rol_descripcion: "artista"}
    ]

   const categoria =[
       {cat_id: 1, cat_descripcion: "fotografia"},
       {cat_id: 2, cat_descripcion: "pintura"},
       {cat_id: 3, cat_descripcion: "escultura"},
       {cat_id: 4, cat_descripcion: "arte digital"},  
   ]


   const usuario = [
       {usuario_id: uuidv4(), usuario_name: "Facundo", usuario_email: "facundo@mail.com", usuario_token: "lk12kl321", usuario_imagen:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/User_with_smile.svg/1024px-User_with_smile.svg.png", usuario_password:"1234", rol_id:2},
       {usuario_id: uuidv4(), usuario_name: "Martin", usuario_email: "martin@mail.com", usuario_token: "lk12kdsadasl321", usuario_imagen:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/User_with_smile.svg/1024px-User_with_smile.svg.png", usuario_password:"1234", rol_id:2}
   ]

   const obraArte = [
       {oa_id: uuidv4(), oa_name: "Pintura 1", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "Pintura 2", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "Pintura 3", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "Pintura 4", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "Pintura 5", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "Pintura 6", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "Foto prueba", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "imagen 99 ", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "Fotografia cerros", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "Ejemplo", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "Pintura 100", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "example", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "amanecer", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "mosaicos", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 0, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[2].cat_id},
       {oa_id: uuidv4(), oa_name: "Paisajes", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 1, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[1].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "paisajes2", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 100, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[3].cat_id},
       {oa_id: uuidv4(), oa_name: "zazazaza", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 510, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[1].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "lalalala", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[1].usuario_id, cat_id: categoria[2].cat_id},
       {oa_id: uuidv4(), oa_name: "Pintura 1", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id},
       {oa_id: uuidv4(), oa_name: "foto edificios", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[0].cat_id},
       {oa_id: uuidv4(), oa_name: "foto realista", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[1].usuario_id, cat_id: categoria[0].cat_id},
       {oa_id: uuidv4(), oa_name: "practicas", oa_descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper tortor magna, quis malesuada enim viverra ac. Nam vel felis gravida, convallis massa a, dictum odio. Ut vehicula, lacus eget tempor commodo, massa elit lacinia lacus, sed rutrum erat augue nec sapien.", oa_fechaCreacion: "01-05-1998", oa_oculto: false, oa_likes: 10, oa_imagen_obra: "https://cdn2.chicmagazine.com.mx/uploads/media/2020/07/29/gogh-pinturas-obras-famosas-foto.jpg", usuario_id: usuario[0].usuario_id, cat_id: categoria[1].cat_id}
   ]

    return {roles, categoria, usuario, obraArte}
}
module.exports = { createData };